### PR TITLE
Adding support for injectable instrumentation #38

### PR DESCRIPTION
**Pull request by NicholasAzar**
In regards to: #38

### CODE REVIEW

**Comment by stevehu** [comment]
@NicholasAzar Thanks for the quick implementation. This will give users more flexibility to inject logic into the handler. I see you are using a static class to load instrumentation. Do you think startup hook will work in this case? I am new with this instrumentation and still in the reading process in order to understand it. Is it possible to have a test case or example to show users how to use it?

**Comment by NicholasAzar** [comment]
@stevehu Could you please clarify the reasons for using a startup hook in this case?

Are you expecting it to look something like this?
```java
public class InstrumentationStartupHookProvider implements StartupHookProvider {

    private static Instrumentation graphqlInstrumentation;
    private static Instrumentation graphqlSubscriptionInstrumentation;

    @Override
    public void onStartup() {
        InstrumentationProvider instrumentationProvider = SingletonServiceFactory.getBean(InstrumentationProvider.class);
        if (instrumentationProvider != null) {
            graphqlInstrumentation = instrumentationProvider.getGraphqlInstrumentation();
            graphqlSubscriptionInstrumentation = instrumentationProvider.getGraphqlSubscriptionInstrumentation();
        }
    }

    public static Instrumentation getGraphqlInstrumentation() {
        return graphqlInstrumentation;
    }

    public static Instrumentation getGraphqlSubscriptionInstrumentation() {
        return graphqlSubscriptionInstrumentation;
    }
}

```

Also, I have the example you recently merged, but I'll start taking a look at test cases for these items.

**Comment by NicholasAzar** [comment]
@stevehu My only concern with having this being added as a startup hook is the additional configuration required in service.yml.

I was under the impression that startup/shutdown hooks should be used for lifecyle events... like managing current number of running instances of a service, setting up or tearing down something persistent over the life of the application, or processing runtime arguments in a way that could inject into the business logic (and following that thread IOC in general).

For IOC to be a beneficial pattern in this context however, these startup hooks could be interfaces that rather then implementations. So that the test service.yml could provide a mock InstrumentationStartupHook (or whatever), and it could make sense to have these types of classes that just instantiate static variables. Right?

**Comment by stevehu** [comment]
@NicholasAzar You are right. The service.yml is used for life-cycle management and it is served as a single injection point. We've got a lot of things injected there already and developers are used to it. Most of the object we inject there are singleton objects which are thread-safe and they live the entire life-cycle of the server. Just like you said, this IOC service allows us to swap implementations in design time and runtime. All the framework components are reference implementations only in my opinion, and users can customize/swap any component as they wish. A static class works but it is very hard for users to enhance it or customized it within their application.

**Comment by ddobrin** [comment]
For start-up hook handlers, in addition to lifecycle events such as creation/closing of resources, I would add also time-sensitive operations such as accessing another API for read-only(reference) data retrieval. 
The call can not be executed in the first processed request, due to its time-sensitive nature and concurrency, and the start-up handlers are perfect for that

**Comment by NicholasAzar** [comment]
@stevehu I'm having a hard time wrapping my head around the injection pattern for runtime swapping -- given the fact that these are not interfaces. 
For example, if i needed to mock out the graphqlInstrumentation above for one used in testing. How would that look from the perspective of my test module? Would i provide a whole new service.yml that listed the mocked InstrumentationStartupHook (that hopefully had the same available methods)?

@ddobrin Reference data caching is an interesting example for a startup hook.. but i'm afraid with me brings up more questions then answers :stuck_out_tongue_winking_eye:! Cache eviction and statefulness of the service both seem like items to address. I suppose potentially with supplementing the results of the startup hook with a middleware handler.
This certainly is a topic that i would like to discuss more in depth.

**Comment by stevehu** [comment]
@NicholasAzar Let's have a chat tonight over the phone if you are available. Thanks.

**Pull request merged**
